"""add new column of users

Revision ID: 4d8a15151ab8
Revises: 85a029028423
Create Date: 2017-04-07 20:00:26.262498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8a15151ab8'
down_revision = '85a029028423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###
