"""add disabled column of posts

Revision ID: 63dc3d943c04
Revises: f4cdc3572ae5
Create Date: 2017-04-16 19:31:39.115759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dc3d943c04'
down_revision = 'f4cdc3572ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'disabled')
    # ### end Alembic commands ###
