"""add new columns of posts and comments

Revision ID: 830037cacd3d
Revises: 4d8a15151ab8
Create Date: 2017-04-10 23:29:38.079380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830037cacd3d'
down_revision = '4d8a15151ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    op.drop_column('comments', 'disabled')
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###
